"""Add filename

Revision ID: c5bc40e92f91
Revises: 111bd25c520a
Create Date: 2024-06-13 05:31:23.219971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bc40e92f91'
down_revision = '111bd25c520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_request', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
